FROM debian:stretch-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    build-essential \
    caffe-cpu \
    git \
    python3 \
    python3-dev \
    python3-numpy \
    python3-pip \
    python3-setuptools \
    python3-wheel \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /src/nsfw_model

WORKDIR /src/nsfw_model

RUN wget http://pretrained-models.auth-18b62333a540498882ff446ab602528b.storage.gra5.cloud.ovh.net/image/nsfw/deploy.prototxt

RUN wget http://pretrained-models.auth-18b62333a540498882ff446ab602528b.storage.gra5.cloud.ovh.net/image/nsfw/resnet_50_1by2_nsfw.caffemodel


WORKDIR /src

ADD requirements.txt /src/
RUN pip3 install -r requirements.txt

ADD app_utils.py /src/
ADD classify_nsfw.py /src/
ADD app.py /src/

EXPOSE 5000

ENTRYPOINT ["python3", "app.py"]
